name: Latest blog posts

on:
  schedule:
    # Once a day at 03:00 UTC
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull latest Medium posts into README
        uses: gautamkrishnar/blog-post-workflow@2786e54a01b71aec80a5118c2bd6b5044e842597 # v1
        with:
          feed_list: "https://medium.com/feed/@brilianadeputra"
          max_post_count: 5
